name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy and Restart
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd ${{ secrets.DEPLOY_PATH || '/home/azureuser/brainchit-utils' }}
            echo "📦 Pulling latest code from main branch..."
            git pull origin main
            echo "📥 Installing dependencies..."
            npm install --production
            echo "🔄 Restarting PM2 process..."
            npx pm2 restart brainchit-utils || npx pm2 start server.js --name brainchit-utils
            echo "✅ Deployment complete!"
            npx pm2 status
